Configuration changes and some fixes In this change, we have done several fixes which will make our service startable. That includes: 1. Fix the issue that the stock sycing task's shanghai listing task and shenzhen listing task uses the same column 2. Move PostgresqlDataTypeFactory to dal-jpa-context. That is because databaseInitializer requires it. We need further work to figure out why we have create that bean. 3. Fix the issue that we've incorrectly specify the CORSFilter's location. 4. Change to use hibernate api version to 2.1. Version 2.0 will always produce an exception: http://stackoverflow.com/questions/28062271/java-lang-nosuchmethoderror-javax-persistence-joincolumn-foreignkeyljavax-per